apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aimanager-subscription
  namespace: noi
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  channel: v3.3
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
