apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noi-subscription
  namespace: noi
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  channel: v1.14
  installPlanApproval: Automatic
  name: noi
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
