apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: config-generation
spec:
  tasks:
    - name: git-clone-configs
      params:
        - name: url
          value: >-
            https://github.com/Nordic-MVP-GitOps-Repos/cp4waiops-configuration.git
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: configs
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: git
        - name: basic-auth
          workspace: basic-auth
    - name: create-noi-configmap
      params:
        - name: pathtriggers
          value: configs/primary/agg-p-sql-extensions
        - name: pathconfigmap
          value: gitops/config/resources/evtmanager-objserv-agg-primary-config.yaml
      runAfter:
        - git-clone-gitops
        - git-clone-configs
      taskRef:
        kind: Task
        name: create-noi-configmap
      workspaces:
        - name: git
          workspace: git
    - name: git-clone-gitops
      params:
        - name: url
          value: 'https://github.com/Nordic-MVP-GitOps-Repos/cp4waiops-gitops.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: gitops
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: git
        - name: basic-auth
          workspace: basic-auth
    - name: git-push-config-change
      params:
        - name: BASE_IMAGE
          value: >-
            docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
        - name: GIT_SCRIPT
          value: >-
            cd gitops

            git add config/resources/evtmanager-objserv-agg-primary-config.yaml

            git commit -m "Updated config map based on
            $(tasks.git-clone-configs.results.commit)"

            git push origin HEAD:main
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
        - name: GIT_USER_NAME
          value: <USERNAME>
        - name: GIT_USER_EMAIL
          value: test@example.com
      runAfter:
        - create-noi-configmap
      taskRef:
        kind: ClusterTask
        name: git-cli
      workspaces:
        - name: source
          workspace: git
        - name: basic-auth
          workspace: basic-auth
    - name: oc-rollout-restart
      params:
        - name: SCRIPT
          value: oc rollout restart statefulset/evtmanager-ncoprimary
        - name: VERSION
          value: latest
      runAfter:
        - argocd-task-sync-and-wait
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: noi-config
        - name: revision
          value: main
        - name: flags
          value: '--'
        - name: argocd-version
          value: v2.2.5
      runAfter:
        - git-push-config-change
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
  workspaces:
    - name: git
    - name: basic-auth
