apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cop-sync-pipeline
spec:
  params:
    - default: 'https://github.com/ComposeDev/cp4waiops-configuration.git'
      name: git_configuration_repo
      type: string
    - name: git_user_name
      type: string
    - name: git_user_email
      type: string
  tasks:
    - name: git-clone-configs
      params:
        - name: url
          value: $(params.git_configuration_repo)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: configs
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: git
        - name: basic-auth
          workspace: basic-auth
    - name: copy-cop-files
      params:
        - name: SCRIPT
          value: |
            oc rsync -c impactgui --strategy=tar $(workspaces.manifest-dir.path)/configs/guiserver/COP evtmanager-impactgui-0:/space/opview
      runAfter:
        - git-clone-configs
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: git
  workspaces:
    - name: git
    - name: basic-auth
