apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-noi-configmap
  namespace: noi
spec:
  params:
    - description: the path of the trigger files
      name: pathtriggers
      type: string
    - description: the path of the config map manifest
      name: pathconfigmap
      type: string
  steps:
    - image: 'docker.io/mikefarah/yq:4.24.5'
      name: merge-files
      resources: {}
      script: >
        touch triggers.yaml

        for file in $(workspaces.git.path)/$(params.pathtriggers)/* ; do
          echo "$(basename "$file")"
          cat $file >> triggers.yaml
        done

        sed -i 's/\s*$//g' triggers.yaml

        cat triggers.yaml

        yq -i 'del(.data.agg-p-sql-extensions)'
        $(workspaces.git.path)/$(params.pathconfigmap)

        yq -i '.data.agg-p-sql-extensions = load_str("triggers.yaml")'
        $(workspaces.git.path)/$(params.pathconfigmap) 

        cat $(workspaces.git.path)/$(params.pathconfigmap)
      securityContext:
        runAsUser: 0
  workspaces:
    - name: git
