apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: merge-files-into-manifest
spec:
  params:
    - description: >-
        the path of the files to be merged into yaml manifest. directories will
        be field names, files will be merged as values
      name: pathfiles
      type: string
    - description: the path of the yaml manifest
      name: pathmanifest
      type: string
    - default: 4.24.5
      name: yq-version
      type: string
  steps:
    - image: 'docker.io/mikefarah/yq:$(params.yq-version)'
      name: merge-files
      resources: {}
      script: |
        function traverse() {
          local mergedfile=$(basename $1)
          local yamlpath=$2'.'$mergedfile
          echo -n "" > $(workspaces.inputoutput.path)/merged/$mergedfile
          local scandir=$1
          if [ -f "$1/.mergepath" ]; then
            scandir=$1/$(cat $1/.mergepath)
          fi
          for file in $scandir/*
          do
              if [ ! -d "${file}" ] ; then
                  echo "${file} is a file"
                  cat $file >> $(workspaces.inputoutput.path)/merged/$mergedfile
              else
                  echo "entering recursion with: ${file}"
                  traverse $file $yamlpath
              fi
          done
          if [ -s $(workspaces.inputoutput.path)/merged/$mergedfile ]; then
            sed -i 's/\s*$//g' $(workspaces.inputoutput.path)/merged/$mergedfile
            #cat $(workspaces.inputoutput.path)/merged/$mergedfile
            yq -i 'del('$yamlpath')' $(workspaces.inputoutput.path)/$(params.pathmanifest)
            yq -i $yamlpath' = load_str("$(workspaces.inputoutput.path)/merged/'$mergedfile'")' $(workspaces.inputoutput.path)/$(params.pathmanifest) 
          else
            set -x; rm $(workspaces.inputoutput.path)/merged/$mergedfile
          fi
        }

        mkdir -p $(workspaces.inputoutput.path)/merged
        traverse $(workspaces.inputoutput.path)/$(params.pathfiles) ''
        cat $(workspaces.inputoutput.path)/$(params.pathmanifest)
        sleep 600
      securityContext:
        runAsUser: 0
  workspaces:
    - name: inputoutput
