apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sqlfluff
spec:
  params:
    - default: lint $(workspaces.input.path)
      name: arguments
      type: string
    - default: latest
      name: version
      type: string
  steps:
    - image: 'sqlfluff/sqlfluff:$(params.version)'
      name: sqlfluff
      resources: {}
      script: |
        sqlfluff $(params.arguments)
  workspaces:
    - name: input
