kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  namespace: noi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: vsphere-sc
  volumeMode: Filesystem
