kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-noi-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - noi.ibm.com
      - tekton.dev
      - cert-manager.io
    resources:
      - '*'
  - verbs:
      - create
      - delete
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
