apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noi
  namespace: aiops
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  channel: v1.7
  installPlanApproval: Automatic
  name: noi
  source: ibm-noi-catalog
  sourceNamespace: openshift-marketplace
