apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: tekton-custom-role
rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - list
        - get
    - apiGroups:
        - ""
      resources:
        - pods/exec
      verbs:
        - create
