apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: noi-ci
  annotations:
    argocd.argoproj.io/sync-wave: "500"
spec:
  destination:
    namespace: noi
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ComposeDev/cp4waiops-gitops
    path: ci/resources
    targetRevision: k8s
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
