apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  serviceContinuity:
    continuousAnalyticsCorrelation: false
    isBackupDeployment: false
  ldap:
    mode: standalone
    storageSize: 1Gi
    storageClass: 'ocs-storagecluster-cephfs'
  helmValuesNOI:
    global.service.nodePort.enable: true
  backupRestore:
    enableAnalyticsBackups: false
  version: 1.6.9
  entitlementSecret: ibm-entitlement-key
  clusterDomain: apps.aiops.is.compose.se
  persistence:
    storageClassMinio: 'ocs-storagecluster-cephfs'
    storageSizeMinio: 50Gi
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: 'ocs-storagecluster-cephfs'
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: 'ocs-storagecluster-cephfs'
    storageClassKafka: 'ocs-storagecluster-cephfs'
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: 'ocs-storagecluster-cephfs'
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: 'ocs-storagecluster-cephfs'
    storageClassCouchdb: 'ocs-storagecluster-cephfs'
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: 'ocs-storagecluster-cephfs'
    storageSizeCassandraData: 50Gi
    storageClassElastic: 'ocs-storagecluster-cephfs'
    storageClassImpactGUI: 'ocs-storagecluster-cephfs'
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: 'ocs-storagecluster-cephfs'
    storageClassPostgresql: 'ocs-storagecluster-cephfs'
    storageSizePostgresql: 100Gi
    storageClassPostgresqlWal: 'ocs-storagecluster-cephfs'
    storageSizePostgresqlWal: 100Gi
    storageClassSharedSpark: 'ocs-storagecluster-cephfs'
    storageSizeSharedSpark: 100Gi
  postgresql:
    edbPostgresImage: cp.icr.io/cp/cpd/postgresql:13.8@sha256:91a88a30e9cd2dd5e5d1e8cfb588b12e3852939f777b9e9ddc6657d3bbc10367
    edbPostgresLicenseImage: cp.icr.io/cp/cpd/edb-postgres-license-provider@sha256:fd8339c382e1c5d69184d9c3f299a3da5c9a12a579e0db5e76e86d65be9190fd
    edbPostgresSubscriptionName: cloud-native-postgresql-catalog-subscription
  deploymentType: trial
  topology:
    storageClassElasticTopology: 'ocs-storagecluster-cephfs'
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
    storageSizeSdconapObserver: 5Gi
    storageClassFileObserver: 'ocs-storagecluster-cephfs'
    iafCartridgeRequirementsName: ''
    appDisco:
      enabled: false
    observers:
      alm: false
      ansibleawx: false
      appdynamics: true
      aws: false
      azure: true
      bigcloudfabric: false
      bigfixinventory: false
      cienablueplanet: false
      ciscoaci: false
      contrail: false
      dns: true
      docker: true
      dynatrace: false
      file: true
      gitlab: false
      googlecloud: false
      hpnfvd: false
      ibmcloud: false
      itnm: true
      jenkins: false
      junipercso: false
      kubernetes: true
      newrelic: false
      openstack: false
      rancher: false
      rest: true
      sdconap: false
      servicenow: true
      sevone: true
      taddm: false
      viptela: false
      vmvcenter: true
      vmwarensx: false
      zabbix: false
    netDisco: false
