apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  ldap:
    mode: standalone
    storageSize: 1Gi
    storageClass: 'vsphere-sc'
  helmValuesNOI:
    global.service.nodePort.enable: true
  backupRestore:
    enableAnalyticsBackups: false
  version: 1.6.8
  entitlementSecret: ibm-entitlement-key
  clusterDomain: apps.aiops.is.compose.se
  persistence:
    storageClassMinio: 'vsphere-sc'
    storageSizeMinio: 50Gi
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: 'vsphere-sc'
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: 'vsphere-sc'
    storageClassKafka: 'vsphere-sc'
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: 'vsphere-sc'
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: 'vsphere-sc'
    storageClassCouchdb: 'vsphere-sc'
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: 'vsphere-sc'
    storageSizeCassandraData: 50Gi
    storageClassElastic: 'vsphere-sc'
    storageClassImpactGUI: 'vsphere-sc'
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: 'vsphere-sc'
  deploymentType: trial
  topology:
    storageClassElasticTopology: 'vsphere-sc'
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
    storageClassFileObserver: 'vsphere-sc'
    iafCartridgeRequirementsName: ''
    appDisco:
      enabled: false
    observers:
      alm: false
      ansibleawx: false
      appdynamics: true
      aws: false
      azure: true
      bigcloudfabric: false
      bigfixinventory: false
      cienablueplanet: false
      ciscoaci: false
      contrail: false
      dns: true
      docker: true
      dynatrace: false
      file: true
      gitlab: false
      googlecloud: false
      hpnfvd: false
      ibmcloud: false
      itnm: true
      jenkins: false
      junipercso: false
      kubernetes: true
      newrelic: false
      openstack: false
      rancher: false
      rest: true
      sdconap: false
      servicenow: true
      sevone: true
      taddm: false
      viptela: false
      vmvcenter: true
      vmwarensx: false
      zabbix: false
    netDisco: false
